sudo: required

language: rust
rust:
  - nightly
  - beta
  - stable

os:
  - linux
  - osx

script:
  - sudo mkdir -p /var/empty
  - sudo chmod 555 /var/empty
  - sudo $( which cargo ) test --verbose
