[package]
name = "privdrop"
version = "0.5.6"
description = "Drop privileges on Unix by switching from root to another user or group, with supplementary group control and optional chroot."
authors = ["Frank Denis <github@pureftpd.org>"]
keywords = ["privileges", "drop", "unix", "chroot", "setuid"]
license = "ISC"
homepage = "https://github.com/jedisct1/rust-privdrop"
repository = "https://github.com/jedisct1/rust-privdrop"
categories = ["os::unix-apis"]
edition = "2018"

[dependencies]
libc = "0.2.172"
nix = { version = "0.30.1", features = ["user", "fs"] }
